### ISSUE TITLE
backtesting fresh clone

### ISSUE THREAD

**Issue by generalectric** [GarrettFleischer/PoloniexTradingBot#3]
`initializing

gathering source for BTC_AMP
Traceback (most recent call last):
  File "tradingbot.py", line 182, in <module>
    main()
  File "tradingbot.py", line 138, in main
    source = BacktestDataSource(currency, poloniex, start, period, update_interval / 60)
  File "/home/adm1n/PoloniexTradingBot/trading/data_source.py", line 91, in __init__
    self.main_balance_init = float(balances[self.symbol_main])
KeyError: 'BTC'`

fresh clone trying to run a backtest. simply changed backtest to true. doesnt work with usdt or btc. did i miss something?

**Comment by generalectric** [comment]
ok turned backtesting off got nonce error. created a new key on exchange then it worked... then turned backtesting back on.... and voila.... just as it says.... key error. Very nice work sir!
